version: "3.4"
services:
  videos-web:
    container_name: videos-web
    image: jaskeerat/website:v1
    build:
      context: ./website/
    ports:
      - 80:80
    networks:
    - tracing
  playlists-api:
    container_name: playlists-api
    image: jaskeerat/playlist-api:v1
    build:
      context: ./playlist-api
    environment:
    - "ENVIRONMENT=DEBUG"
    - "REDIS_HOST=playlists-db"
    - "REDIS_PORT=6379"
    - "JAEGER_HOST_PORT=jaeger:6831"
    ports:
    - 81:10010
    networks:
    - tracing
  playlists-db:
    container_name: playlists-db
    image: redis:6.0-alpine
    command: [ "redis-server"]
    port:
      - 6379:6379
    networks:
    - tracing
  videos-api:
    container_name: videos-api
    image: jaskeerat/video-api:v1
    build:
      context: ./video-api
    environment:
    - "ENVIRONMENT=DEBUG"
    - "REDIS_HOST=videos-db"
    - "REDIS_PORT=6379"
    - "JAEGER_HOST_PORT=jaeger:6831"
    #- "DELAY=true"
    #- "FLAKY=true"
    ports:
    - 82:10010
    networks:
    - tracing
  videos-db:
    container_name: videos-db
    image: redis:6.0-alpine
    command: [ "redis-server"]
    port:
      - 6380:6379
    networks:
    - tracing
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    networks:
    - tracing
    ports:
    - 16686:16686
    - 14269:14269
networks: 
  tracing:
    name: tracing